APP_NAME="udemy_terraform"
#PORT_MAPPING="-p 80:80"
#VOLUME_MOUNT="-v ${BASEDIR}:/opt/app -v ${HOME}/.ssh:/root/.ssh -v ${HOME}/.aws:/root/.aws -v /var/run/docker.sock:/var/run/docker.sock"
VOLUME_MOUNT="-v ${BASEDIR}:/opt/app"
DOCKER_RM_OPT="--rm"
#DOCKER_RM_OPT=""
DOCKER_RUN_OPT="--link docker:docker -e DOCKER_CERT_PATH=/certs/client -e DOCKER_TLS_CERTDIR=/certs -e DOCKER_TLS_VERIFY=1 -e DOCKER_HOST=tcp://docker:2376 -v dind-certs-client:/certs/client:ro"
CMD="/bin/echo 'Hello World!'"